# Generated by Django 4.0.5 on 2022-09-03 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_freequote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freequote',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 3, 10, 10, 23, 93911), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 10, 10, 23, 93911)),
        ),
    ]
