# Generated by Django 4.0.5 on 2022-07-21 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldnews',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 15, 34, 23, 847930)),
        ),
    ]
