# Generated by Django 4.0.5 on 2022-08-27 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localnews', '0002_alter_localnews_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localnews',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 14, 56, 25, 979860)),
        ),
    ]
