# Generated by Django 4.0.5 on 2022-08-28 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localnews', '0003_alter_localnews_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localnews',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 15, 8, 54, 61212)),
        ),
    ]
